### ISSUE TITLE
Add a unit testing framework for server

### ISSUE THREAD

**Issue by Cooryd** [diversemix/malcolm#21]
We need to write unit tests for server side code. This is a good time to assess if Jest is the best option? If so get that up and running with some initial tests on the code we've added.

**Comment by diversemix** [comment]
@petereast / @erezmus  ... is this linked to #38

**Comment by erezmus** [comment]
@diversemix probably, we might need to coordinate on that

**Comment by erezmus** [comment]
I'll wait for #38 to be merged in before i put in a PR

My objective is to add some unit tests to see how easy it is to test type ORM

We should also probably add testing doc

**Comment by erezmus** [comment]
Did a bit of digging for typeorm testing and added a basic unit test. It seems that we can instantiate entities without any db which is good.
