### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by diversemix** [diversemix/malcolm#37]
We need to implement our own `passport` strategy for authentication using the profiles service. (see https://docs.nestjs.com/techniques/authentication)

It is worth considering that longer term we need to consider/introduce other ways of authentication to allow for reuse. Therefore, consider making the strategy configurable.

update
---
The scope of this ticket, and it's associated PR (#46 ) is limited to:
- Boilerplate to intercept JWT in request headers
- A testing endpoint to test the restriction

The next steps, to be handled in other tickets:
- Something to lookup the user object, to verify that the `userId` is correct, and fetch data about the user such as their role in the system #50
- Using the `GqlAuthGuard` in appropriate resolvers #51
- The mechanism to exchange tokens with other eLife systems (i.e. so the user can log in) #52
- The necessary interstitial pages #53

**Comment by petereast** [comment]
If NestJS uses Passport by default, we might be able to use this: http://www.passportjs.org/packages/passport-orcid/

**Comment by diversemix** [comment]
We have used this before in the past - but we need to auth with the profiles service ... the fact it uses ORCID is an internal implementation detail..

**Comment by petereast** [comment]
Some subtasks:
- [ ] Add Passport (according to NestJS docs)
- [ ] Write a nest UserService that connects to the `profiles` service
- [ ] Connect the passport strategy to the UserService
- [ ] ...I think that's it - it seems that Nest will just magic everything together more or less

**Comment by diversemix** [comment]
Yeah that is what I hope - let's go for it ... I'd be interested in knowing if we could do this as config so that we could swap out the auth module for another one in the case of it being used by another publisher.

**Comment by petereast** [comment]
It's a bit tricky - if we're going for parity with `elife-xpub`, we can't just follow the nestjs tutorial - we need to roll our own services etc. I don't know if passport is the right thing for us to use for this scheme - I'm really not comfortable with the amount of magic. Maybe we should have a look at this https://docs.nestjs.com/guards and see how we could implement this sort of thing ourselves (look @diversemix  there's even a section on RBAC)

**Comment by diversemix** [comment]
Yes I have read that
