### ISSUE TITLE
Optimise production loaders in webpack config

### ISSUE THREAD

**Issue by Cooryd** [diversemix/malcolm#43]
Currently we have a default set of loaders used for both dev and prod builds. We should look at what can be optimised for production builds and split these.

Example: 

`{loader: 'style-loader', options: {sourceMap: true}},`

should be replaced with 

`MiniCssExtractPlugin.loader,` 

in prod. See https://github.com/webpack-contrib/sass-loader#in-production

**Comment by erezmus** [comment]
I might try using OptimizeCSSAssetsPlugin with cssnano instead

https://survivejs.com/webpack/optimizing/minifying/#minifying-css
