### ISSUE TITLE
Discussion: Optional types

### ISSUE THREAD

**Issue by petereast** [diversemix/malcolm#72]
We can improve type safety and software reliability by using optional types from a library like `funfix`. This isn't a massive change but it might not be immediately obvious to everyone.

**Comment by petereast** [comment]
I've added a bit of optional goodness in with #77, It means we won't have to deal with when something is `null` or `undefined`

**Comment by diversemix** [comment]
Thanks for adding this ... I don't really see there is a need for discussion its just good coding. What might be up for discussion is the actual library `funfix` itself. So going to close this and let anyone how wants to raise concerns raise another ticket :)
