### ISSUE TITLE
Define interfaces & topologies

### ISSUE THREAD

**Issue by diversemix** [diversemix/malcolm#8]
GraphQL
Module/Controller?
Database

**Comment by petereast** [comment]
*_ T H I N S L I C E _* - The graphql endpoint - #7 

```graphql
type Submission {
  id: ID!
  title: String!
}

type Query {
  getSubmissions: [Submission!]!
}
```

**Comment by hdrury1** [comment]
I was under the impression this was done @diversemix?

**Comment by diversemix** [comment]
yes... this was done as part of the other tickets.
